nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

npmScopes:
  vsm:
    npmRegistryServer: https://nexus.tmapmp.com/repository/npm-private/
  "tmap-web-lib":
    npmRegistryServer: https://nexus.tmapadmin.com/repository/npm-private/

yarnPath: .yarn/releases/yarn-3.6.4.cjs
